---
title: "Week 3: Working with files in the Unix shell"
pagetitle: "Week 3 overview"
date: 2026-09-05
number-sections: false
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://go.osu.edu/bioinformatics-core
      - name: Dept. of Plant Pathology, Ohio State University
        url: https://plantpath.osu.edu
other-links:
  - text: "w3a: Sequence file types"
    icon: bookmarks
    href: w3a_file-overview.html
  - text: "w3b: Shell files I"
    icon: bookmarks
    href: w3b_shellfiles.html
  - text: "w3c: Shell files II"
    icon: bookmarks
    href: w3c_shellfiles.html
  - text: "Week 3 exercises"
    icon: pencil
    href: w3_exercises.html
bibliography: ../references.bib
---

---------

<br>

## Overview

This week, we will focus on working with files in the Unix shell.
Because we're going to start working with (DNA/RNA/protein) sequence files,
you'll also get introduced to various types of sequence files.
Finally, you'll learn about the specific files from the example dataset
you'll work with throughout the course.

## Learning goals & lectures

#### [**Unix shell basics**](./w2c_shell.qmd) _(Thursday)_

- What the Unix shell is and what you can do with it
- Why it can be beneficial to use a command-line interface in general,
  and the Unix shell specifically
- How Unix commands are stuctured
- How to navigate around your computer with Unix commands

##### [**Sequence file types and the example dataset**](./w3a_file-overview.qmd) _(Tuesday)_

- What FASTA, FASTQ, and GFF/GTF files are for and what they look like
- How base-call quality scores are coded in FASTQ files
- What the experimental design the course's example dataset's study looks like
- Which files are in our example data set

##### [**Working with files in the Unix shell I: The shell as a file browser**](./w3b_shellfiles.qmd) _(Tuesday/Thursday)_

Learn to use Unix shell commands to:

- Create, copy, move, rename and delete directories and files
- Select multiple files with a shell wildcard

##### [**Working with files in the Unix shell II: Viewing, summarizing and manipulating files**](./w3c_shellfiles.qmd) _(Thursday)_

Learn to use Unix shell commands to:

- View the contents of text files in various ways
- Use redirection and the pipe to flexibly process the output of commands
- Search within, manipulate, and extract information from text files

## Readings

- @garrigós2025:
 _Two avian Plasmodium species trigger different transcriptional tesponses on their vector Culex pipiens_\
 This is the paper associated with the dataset we will use throughout the course,
 starting this week.

## Assignments & exercises

- [Week 3 exercises](./w3_exercises.qmd)
- _No assignments this week_

## Further resources

- @buffalo2015 ([OSU library link](https://search.library.osu.edu/permalink/01OHIOLINK_OSU/1oqfg3i/alma991085518416808507))
  -- Chapter 3: "_Remedial Unix Shell_"
