project:
  type: website
  render: #https://quarto.org/docs/websites/index.html#render-targets
    - "*qmd"
    - "!removed/"
    - "!bonus/"
    #- "!week05/"
    #- "!week06/"
    #- "!week07/"
    - "!week08/"
    - "!week09/"
    - "!week10/"
    - "!week11/"
    - "!week12/"
    - "!week13/"
    - "!week14/"
    - "!week15/"
    - "!week16/"

website:
  title: "PRACS-AU26"
  favicon: img/favicon.png
  site-url: https://cfaes-bioinfo.github.io/pracs-au26
  repo-url: https://github.com/cfaes-bioinfo/pracs-au26
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    background: "#666666"
    logo: img/logo4c.png
    left:
      - icon: house-fill
        text: " "
        href: index.qmd
        aria-label: "Home"
      - text: Week overviews
        menu: 
        - text: "Week 1: Omics data"
          href: week01/w1_overview.qmd
        - text: "Week 2: OSC, project organization, and Markdown"
          href: week02/w2_overview.qmd
        - text: "Week 3: Unix shell -- basics"
          href: week03/w3_overview.qmd
        - text: "Week 4: Unix shell -- working with files"
          #href: week04/w4_overview.qmd
        - text: "Week 5: Version control with Git and GitHub"
          #href: week05/w5_overview.qmd
        - text: "Week 6: Software management at OSC"
          #href: week06/w6_overview.qmd
        - text: "Week 7: Shell scripts and CLI tools"
          #href: week07/w7_overview.qmd
        - text: "Week 8: Using generative and agentic AI"
          #href: week08/w8_overview.qmd
        - text: "Week 9: Slurm batch jobs at OSC"
          #href: week09/w9_overview.qmd
        - text: "Week 10: Workflow and data management"
          #href: week10/w10_overview.qmd
        - text: "Week 11: Nextflow nf-core pipelines"
          #href: week11/w11_overview.qmd
        - text: "Week 12: R -- basics"
          #href: week12/w12_overview.qmd
        - text: "Week 13: R -- data wrangling & visualization"
          #href: week13/w13_overview.qmd
        - text: "Week 14: R -- Quarto notebooks"
          #href: week14/w14_overview.qmd
        - text: "Week 15: R -- for omics data"
          #href: week15/w15_overview.qmd
        - text: "Week 16: Recap & Student presentations"
          #href: week16/w16_overview.qmd
      - text: "Exercises"
        menu:
        - text: "Week 2: Project organization & Markdown"
          #href: week02/w2_exercises.qmd
        - text: "Week 4: Unix shell -- working with files"
          #href: week04/w4_exercises.qmd
        - text: "Week 6: OSC software"
          #href: week06/w6_exercises.qmd
        - text: "Week 8: Generative AI"
          #href: week08/w8_exercises.qmd
        - text: "Week 10: Workflow and data management"
          #href: week10/w10_exercises.qmd
        - text: "Week 12: R basics"
          #href: week12/w12_exercises.qmd
        - text: "Week 13: R data wrangling and visualization"
          #href: week13/w13_exercises.qmd
        - text: "Week 14: Quarto notebooks"
          #href: week14/w14_exercises.qmd
        - text: "Week 15: R for omics data"
          #href: week15/w15_exercises.qmd
        - text: "--------"
      - text: "Assignments"
        menu:
        - text: "GRADED:"
        - text: "GA1: Markdown and Unix shell (Week 3)"
          #href: GA/GA1.qmd
        - text: "GA2: Version control (Week 5)"
          #href: GA/GA2.qmd
        - text: "GA3: Shell scripts (Week 7)"
          #href: GA/GA3.qmd
        - text: "GA4: Slurm batch jobs (Week 9)"
          #href: GA/GA4.qmd
        - text: "GA5: Nextflow pipelines (Week 11)"
          #href: GA/GA5.qmd
        - text: "--------"
        - text: "UNGRADED:"
        - text: "UA1: Pre-course survey (week 1) {{< fa external-link >}}"
          href: https://forms.cloud.microsoft/r/wqriyRJSmd
          target: _blank
        - text: "UA2: OSC account setup (week 1)"
          href: UA/UA2.qmd
        - text: "UA3: GitHub account setup (week 5)"
          #href: UA/UA3.qmd
        - text: "UA4: Local VS Code setup (week 7)"
          #href: UA/UA4.qmd
        - text: "UA5: Post-course survey (week 16) {{< fa external-link >}}"
          #href: TODO
          #target: _blank
      - text: "Final project"
        menu:
        - text: "General information"
          #href: FP/FP-info.qmd
        - text: "FP1: Proposal (week 12)"
          #href: FP/FP1.qmd
        - text: "FP2: Progress report (week 14)"
          #href: FP/FP2.qmd
        - text: "FP3: Oral presentation (week 16)"
          #href: FP/FP3.qmd
        - text: "FP4: Final submission (week 16)"
          #href: FP/FP4.qmd
    right:
      - text: Other
        menu:
        - text: "Literature references"
          #href: ref/refs.qmd
        - text: "Further resources"
          #href: ref/further_resources.qmd
        - text: "-----"
        - text: "Optional self-study material:"
        - text: "Advanced version control"
          # href: bonus/git.qmd
        - text: "Software management with Conda"
          # href: bonus/conda.qmd
        - text: "Advanced shell scripting"
          # href: bonus/shell-scripting.qmd
        - text: "Additional data management notes"
          # href: bonus/data.qmd
        - text: "SSH connections"
          # href: bonus/ssh.qmd
      - text: About
        href: ref/about.qmd
      - text: "<i class='fa-solid fa-graduation-cap' aria-label='CarmenCanvas' title='CarmenCanvas'></i>"
        href: https://osu.instructure.com/courses/213814
        target: _blank
      - text: "<i class='fa-solid fa-desktop' aria-label='OSC OnDemand' title='OSC OnDemand'></i>"
        href: https://ondemand.osc.edu
        target: _blank
    tools:
      - icon: github
        aria-label: "The GitHub repo for this website"
        menu:
          - text: Source code
            url:  https://github.com/cfaes-bioinfo/pracs-au26
            target: _blank
          - text: Report an issue
            url:  https://github.com/cfaes-bioinfo/pracs-au26/issues/new
            target: _blank
  page-footer:
    left: |
      2026, Jelmer Poelstra, [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)   ![](http://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc.png){width="10%"}
    center: |
      ![](/img/CFAES-Horiz-RGBHEX.svg){width="40%"}
    right:
      - icon: github
        href: https://github.com/cfaes-bioinfo/pracs-au26
        aria-label: "The GitHub repo for this website"
        #https://mine-cetinkaya-rundel.github.io/quarto-tip-a-day/posts/25-aria-labels/

format:
  html:
    css: styles.css
    theme: [cosmo, theme_web.scss]
    highlight-style: atom-one
    toc: true
    number-sections: true
    number-depth: 3
    grid:
      body-width: 850px
    self-contained: true

execute:
  freeze: auto
  engine: knitr
  eval: true
editor: source

knitr:
  opts_chunk:
    class-output: regular-r-output
    class-message: regular-r-output
    class-warning: warning-r-output
    class-error: error-r-output
