---
number-sections: false
toc: false
format:
  html:
    grid:
      body-width: 900px
language:
  title-block-published: "Presented on"
  title-block-modified: "Page last modified"
---

<h4 align="center" style="font-size:30px">
[**Practical Computing Skills for Omics Data**]{style="color:var(--color-primary); font-family:'BuckeyeSerif', Georgia, serif; font-weight:700; font-size:1.20em"} <br> [Ohio State PLNTPTH 5006 – Autumn 2026]{style="color:#666666; font-size:0.9em"}
</h4>

<hr style="width:30%; margin:-5px auto 0 auto; border:1px solid #444343;">

<hr style="height:5pt; visibility:hidden;" />

| Week                          | Monday topic                                                                                                  | Wednesday topic                                                                              |  Ex./GA[^1]   |    FP[^2]    |
| :---: | --- | --- | :-----------: | :----------: |
| [01](week01/w1_overview.qmd)  |                                                                                                               | 08/26: [Course intro](week01/w1a_course-intro.qmd) & [Omics data](week01/w1b_omics-data.qmd) |               |              |
| [02](week02/w2_overview.qmd)  | 08/31: [Project organization](week02/w2a_project-org.qmd) & [OSC intro](/week02/w2b_osc.qmd)                  | 09/02: [VS Code](week02/w2c_vscode.qmd) & [Markdown](week02/w2d_markdown.qmd)                | [Ex.1]{.teal} |              |
| [03](week03/w3_overview.qmd)  | [_Labor day_]{style="color:#bb0000"}                                                                          | 09/09: [Unix shell -- basics](week03/w3a_shell-basics.qmd)                                   | [GA1]{.amber} |              |
| [04](week04/w4_overview.qmd)  | 09/14: [Genomics files](week04/w4a_genomics-files.qmd) & [Unix shell -- files I](week04/w4b_shell-files1.qmd) | 09/16: [Unix shell -- files II](week04/w4c_shell-files2.qmd)                                 | [Ex.2]{.teal} |              |
| [05](week05/w5_overview.qmd)  | 09/21: [Version control -- Git](week05/w5a_git.qmd)                                                           | 09/23: [Version control -- GitHub](week05/w5b_github.qmd)                                    | [GA2]{.amber} |              |
| [06](week06/w6_overview.qmd)  | 09/28: [OSC -- beyond the basics](week06/w6a_osc.qmd)                                                         | 09/30: [OSC -- software management](week06/w6b_software.qmd)                                 | [Ex.3]{.teal} |              |
| [07](week07/w7_overview.qmd)  | 10/05: [Shell scripting I](week07/w7a_scripts.qmd)                                                            | 10/07: [Shell scripting II](week07/w7b_cli-tools.qmd) & [III](week07/w7c_tricks.qmd)         | [GA3]{.amber} |              |
| [08](week08/w8_overview.qmd)  | 10/12: [GenAI for coding I](week08/w8a_genAI.qmd)                                                             | 10/14: [GenAI for coding II](week08/w8b_copilot.qmd)                                         | [Ex.4]{.teal} |              |
| [09](week09/w9_overview.qmd)  | 10/19: [Slurm batch jobs I](week09/w9a_slurm1.qmd)                                                            | 10/21: [Slurm batch jobs II](week09/w9b_slurm2.qmd)                                          | [GA4]{.amber} |              |
| [10](week10/w10_overview.qmd) | 10/26: [Workflow management](week10/w10a_workflow.qmd)                                                        | 10/28: [Data management](week10/w10b_data.qmd)                                               | [Ex.5]{.teal} |              |
| [11](week11/w11_overview.qmd) | 11/02: [Nextflow/nf-core pipelines I](week11/w11a_nfcore.qmd)                                                 | 11/04: [Nextflow/nf-core pipelines II](week11/w11b_nfcore2.qmd)                              | [GA5]{.amber} |              |
| [12](week12/w12_overview.qmd) | 11/09: [R -- basics](week12/w12a_r-basics.qmd)                                                                | [_Veteran's day_]{style="color:#bb0000"}                                                     | [Ex.6]{.teal} | [FP1]{.blue} |
| [13](week13/w13_overview.qmd) | 11/16: [R -- data wrangling](week13/w13a_data-wrangling.qmd)                                                  | 11/18: [R -- data visualization](week13/w13b_data-viz.qmd)                                   | [Ex.7]{.teal} |              |
| [14](week14/w14_overview.qmd) | 11/23: [R -- Quarto notebooks](week14/w14a_quarto.qmd)                                                        | [_Thanksgiving_]{style="color:#bb0000"}                                                      | [Ex 8]{.teal} | [FP2]{.blue} |
| [15](week15/w15_overview.qmd) | 11/30: [R for omics data I](week15/w15a_bioconductor.qmd)                                                     | 12/02: [R for omics data II](week15/w15b_deseq.qmd)                                          | [Ex.9]{.teal} |              |
| [16](week16/w16_overview.qmd) | 12/07: [Recap](week16/w16a_recap.qmd) & [Student presentations I](FP/FP3.qmd)                                               | 12/09: [Student presentations II](FP/FP3.qmd)                                                             |               | [FP4]{.blue} |

: {.striped .hover tbl-colwidths="[8,40,38,5,9]"}

<hr style="height:1pt; visibility:hidden;" />

::: callout-note
### Weekly course activities (For Zoom links, visit CarmenCanvas)
- **Lectures**: Monday & Wednesday 1:50–3:10 pm
- **Jelmer's office hours**: Thursday 1–3 pm
- **Kelsey's office hours**: Monday 11 am – 1 pm
- **Recitation**: day and time TBA
:::

[^1]: Ex. = Exercises (ungraded); GA = Graded Assignment
[^2]: FP = Final Project

<style>
/* Hide the footnote list at the bottom of the page */
section#footnotes {
  display: none !important;
}

/* Hide the line divider above the appendix */
#quarto-appendix.default {
  border-top: none !important;
}
</style>

<!----
Previous holiday color: #9c3f8f

::: legend2
<hr style="height:1pt; visibility:hidden;" />
{{< fa book >}} = Week overview page       Ex. = Exercises       GA = Graded Assignment       FP = Final Project
:::
--->
