---
title: "Week 1: Intro to the course and to omics data"
pagetitle: "Week 1 overview"
number-sections: false
date: 2026-08-26
date-modified: last-modified
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation:
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://go.osu.edu/bioinformatics-core
      - name: Dept. of Plant Pathology, Ohio State University
        url: https://plantpath.osu.edu
language:
  title-block-published: "Week starts on"
  title-block-modified: "Page last modified"
  other-links-title: "Also this week"
other-links:
  - text: "w1a: Course intro"
    icon: easel
    href: w1a_course-intro.html
  - text: "w1b: Omics data"
    icon: easel
    href: w1b_omics-data.html
  - text: "Ungraded Assignment: OSC account setup"
    icon: pencil
    href: ../UA/UA2.html
bibliography: ../references.bib
---

------------------------------------------------------------------------

<hr style="height:1pt; visibility:hidden;" />

## Overview

Welcome to the autumn 2026 edition of the PLNTPTH 5006 course,
Practical Computing Skills for Omics Data!
In this first week of the course,
you will get an overview of the course's contents
and an introduction to omics data.

::: callout-note
#### What is this website for?

This is the GitHub website for the course.
It contains the course materials, including lecture slides, readings, and assignments.
In other words, it contains most of the material you might normally find in CarmenCanvas.
In this course, CarmenCanvas is only used for course announcements, grades,
and a course calendar that includes assignment deadlines.
:::

## Learning goals

Across the following two slide decks, you will learn:

#### A) [**Introduction to the course**](./w1a_course-intro.qmd)

- What to expect from this course.
- Which tools and programming languages we will use.
- What is expected of you during this course.

#### B) [**An overview of omics data**](./w1b_omics-data.qmd)

- What omics data is.
- What the main high-throughput sequencing technologies are.
- How Illumina sequence libraries are structured.
- What reference genomes are, and what they are good for.

*We most likely won't finish the second part on Wednesday ---*
*we'll continue it next Monday.*

## Assignments & exercises

- **Ungraded Assignment 1**: [Pre-course survey {{< fa external-link >}}](https://forms.cloud.microsoft/r/wqriyRJSmd){target="_blank"} &nbsp; [*Deadline: Tue Aug 25, 5 pm*]{style="color:var(--color-primary)"}

- **Ungraded Assignment 2**: [Ohio Supercomputer Center account setup](/UA/UA2.qmd) &nbsp; [*Deadline: Sun Aug 30*]{style="color:var(--color-primary)"}

## Readings

- ["Overview of Illumina Sequencing by Synthesis Workflow"](./w1b_omics-data.html#/video-of-illumina-technology)
  Watch this 5-minute video to learn a bit more about how Illumina sequencing works.
  This is meant to provide a bit more background,
  given that the example data in this course will be from Illumina sequencing.
  It's a very quick overview and you don't need to understand all the details!

- @poinsignon2023: *Working with omics data: An interdisciplinary challenge at the crossroads of biology and computer science*
  ([OSU proxy link {{< fa external-link >}}](https://link-springer-com.proxy.lib.ohio-state.edu/protocol/10.1007/978-1-0716-3195-9_10){target="_blank"})\
  This book chapter provides an overview of different kinds of omics data.
  It is the most suitable introduction to omics data I could find, despite two caveats.
  First, you may find it striking that it appeared in a book called
  "Machine Learning for Brain Disorders",
  but the chapter itself is not field-specific at all.
  Second, while it contains an unusual number of typos, there are no serious errors.

::: {.callout-note appearance="simple"}
You can do weekly readings at your own pace at some point during the week.
If we discuss a reading in class, it will be in the following week.
:::

## Optional self-study material

### Introductory omics papers

Consider reading **one** of the following papers ---
browse through the paper titles, and see if any spark your interest.
Many of these present omics and HTS data in a more **field-specific context**,
such as that of plant pathology:

- @lee2023: *The principles and applications of high-throughput sequencing technologies*
  ([open access link {{< fa external-link >}}](https://www.ksdb.org/archive/view_article?pid=dr-27-1-9){target="_blank"})
- @nizamani2023: *High-throughput sequencing in plant disease management: a comprehensive review of benefits, challenges, and future perspectives* ([OSU proxy link {{< fa external-link >}}](https://link-springer-com.proxy.lib.ohio-state.edu/article/10.1186/s42483-023-00199-5){target="_blank"})
- @aragona2022: *New-generation sequencing technology in diagnosis of fungal plant pathogens: A dream comes true?* ([open access link {{< fa external-link >}}](https://pmc.ncbi.nlm.nih.gov/articles/PMC9320658/){target="_blank"})
- @mahmood2022: *Multi-omics revolution to promote plant breeding efficiency* ([open access link {{< fa external-link >}}](https://www.frontiersin.org/journals/plant-science/articles/10.3389/fpls.2022.1062952/full){target="_blank"})
- @pinto2024: *Sequencing-based analysis of microbiomes* ([OSU proxy link {{< fa external-link >}}](https://www-nature-com.proxy.lib.ohio-state.edu/articles/s41576-024-00746-6){target="_blank"})
- @manzoni2018: *Genome, transcriptome and proteome: the rise of omics data and their integration in biomedical sciences* ([OSU proxy link {{< fa external-link >}}](https://academic-oup-com.proxy.lib.ohio-state.edu/bib/article/19/2/286/2562648){target="_blank"})
- @vonderheyden2025: *Advancing species conservation and management through omics tools* ([OSU proxy link {{< fa external-link >}}](https://onlinelibrary-wiley-com.proxy.lib.ohio-state.edu/doi/full/10.1111/1755-0998.14123){target="_blank"})
