---
title: "Week 5: Version control with Git & GitHub"
pagetitle: "Week 5 overview"
number-sections: false
date: 2026-09-21
date-modified: last-modified
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://go.osu.edu/bioinformatics-core
      - name: Dept. of Plant Pathology, Ohio State University
        url: https://plantpath.osu.edu
other-links:
  - text: "w5a: Version control with Git"
    icon: book
    href: w5a_git.html
  - text: "w5b: Remotes on GitHub"
    icon: book
    href: w5b_github.html
  - text: "Ungraded assignment 3: GitHub account"
    icon: pencil
    href: ../UA/UA3.html
  - text: "Graded assignment 2"
    icon: pencil-square
    href: ../GA/GA2.html
  - text: "Optional self-study: Advanced Git"
    icon: book
    href: ../bonus/git.html
language:
  title-block-published: "Week starts on"
  title-block-modified: "Last modified"
  other-links-title: "Also this week"
bibliography: ../references.bib
---

---------

<hr style="height:1pt; visibility:hidden;" />

## Overview

This week, you will learn about the why and how of storing different versions of
files using Git, a formal Version Control System (VCS) --
and sharing the resulting repositories on the GitHub website.

## Lectures & Learning goals

Some of the things you will learn this week across the two lectures are:

#### A) [Version control with Git](./w5a_git.qmd) _(Monday)_

- Understand why it's a good idea to use a formal Version Control System (VCS)
  for research projects
- Learn the basics of creating version control repositories with Git,
  the most widely used VCS

#### B) [Remote repositories on GitHub](./w5b_github.qmd) _(Wednesday)_

- Learn how to put your local repositories online at GitHub,
- How to keep local and online ("remote") repositories synced

## Assignments and exercises

- **Ungraded assignment**: [Create a GitHub account](/UA/UA3.qmd) [_(Do this before Wednesday's class)_]{style="color:#bb0000"}
- **Graded assignment 2**: [Unix shell and Git](/GA/GA2.qmd) [_(Due 9/27)_]{style="color:#bb0000"}

## Further resources

- Optional self-study material on this website: [_Branching, collaborating, and undoing_](../bonus/git.qmd)
  - Learn how to use Git branches to safely make experimental changes.
  - Learn how to undo things and "travel back in time" for your project using Git.

- @allesina2019 --- Chapter 2: "_Version Control_"
 ([OSU library link {{< fa external-link >}}](https://search.library.osu.edu/permalink/01OHIOLINK_OSU/1n8rc7n/alma991085862322008507){target="_blank"})
  
- @buffalo2015 --- Chapter 5: "_Git for Scientists_"
  ([OSU library link {{< fa external-link >}}](https://search.library.osu.edu/permalink/01OHIOLINK_OSU/1oqfg3i/alma991085518416808507){target="_blank"})
  
- For more background on why to use version control,
  and another perspective on Git basics,
  I highly recommend @bryan2017:
  _"Excuse me, do you have a moment to talk about version control?"_
  Note that some of the contents assumes you are an R user.
