---
title: "Week 12: Introduction to R"
pagetitle: "Week 12 overview"
date: 2026-11-09
date-modified: last-modified
author:
  - name: Menuka Bhandari
    #orcid: 0000-0002-3514-7462
    email: bhandari.72@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://go.osu.edu/bioinformatics-core
      - name: Dept. of Plant Pathology, Ohio State University
        url: https://plantpath.osu.edu
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
other-links:
  - text: "w12a: Intro to R and RStudio"
    icon: bookmarks
    href: w12a_r-basics.html
  - text: "w12b: R data structures and data types"
    icon: bookmarks
    href: w12b_data.html
  - text: "w11c: Data frames in R"
    icon: bookmarks
    href: w11c_data-frames.html
  - text: "Week 12 exercises"
    icon: pencil
    href: w12_exercises.html
language:
  title-block-published: "Week starts on"
  title-block-modified: "Last modified"
  other-links-title: "Also this week"
---

------------------------------------------------------------------------

<hr style="height:1pt; visibility:hidden;" />

## Overview

This week, we will cover the basics of the R language - we will learn about R and RStudio interface, data structures and
data types in R, and working with tabular data in R. R is a great tool for
statistical analysis and visualization of any kind of data,
including omics data sets.

## Lectures & Learning goals

Some of the things you will learn this week:

#### [Introduction to R and RStudio](./w12a_r-basics.qmd)

-   The RStudio layout and the functions of the different panes and tabs
-   The basics of interacting with R by using R as a calculator
-   Defining a variable/object in R, and assigning values/data to them
-   Calling R functions
-   Installing and loading R packages
-   Getting help in R

#### [R vectors and data types](./w12b_data.qmd)

-   The vector data structure
-   Data types - `character, integer, double and logical`

#### [Working with tabular data in R](./w11c_data-frames.qmd)

-   The data frame data structure, and different functions to reorganize and modify data frames
-   The matrix data structure

## Assignments and exercises

- [Exercises for this week](./w12_exercises.qmd)

## Further resources

-   [R for Data Science- Second Edition by Hadley Wickham, Mine Cetinkaya-Rundel and Garrett Grolemund](https://r4ds.hadley.nz/)
