---
title: "Week 11: Running nf-core pipelines"
pagetitle: "Week 11 overview"
date: 2026-11-02
date-modified: last-modified
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://go.osu.edu/bioinformatics-core
      - name: Dept. of Plant Pathology, Ohio State University
        url: https://plantpath.osu.edu
other-links:
  - text: "w11a: Running an nf-core pipeline"
    icon: book
    href: w11a_nfcore.html
  - text: "w15b: Course recap"
    icon: book
    href: w15b_recap.html
  - text: "Week 15 exercises"
    icon: pencil
    href: w15_exercises.html
language:
  title-block-published: "Week starts on"
  title-block-modified: "Last modified"
  other-links-title: "Also this week"
bibliography: ../references.bib
---

--------------------------------------------------------------------------------

<hr style="height:1pt; visibility:hidden;" />

## Overview

This week, we will mainly cover how you can run a bioinformatics pipeline
written in the Nextflow language and developed as part of the nf-core initiative.
That will take up the Monday meeting and part of Wednesday's.
On Wednesday, we will also have a brief course recap and Q&A session.

## Learning goals

Specifically, you will learn:

#### Lecture A: [Running nf-core pipelines](./w11a_nfcore.qmd)

- Why you may want to use pipelines like those made by the nf-core initiative
- What the nf-core _rnaseq_ pipeline does, and when you would want to use it
- How these pipelines can be run with a single command,
  while they submit jobs to the Slurm scheduler at OSC.
- The difference between general Nextflow options and pipeline-specific options
  when running such a pipeline.
- How to set up inputs and outputs for such a pipeline,
  including the distinction between a final output dir and a "work dir".
- How to monitor pipeline progress
- How to restart a pipeline run using the `-resume` option
- How to find and interpret the output files produced by the pipeline

#### Lecture B: [Course recap](./w15b_recap.qmd)

- An overview of the topics covered in this course
- Answers to any remaining questions you may have

## Readings

- @ewels2020: "*The nf-core framework for community-curated bioinformatics pipelines*"

## Further resources

- @ditommaso2017: "*Nextflow enables reproducible computational workflows*"
