---
title: "Week 13 exercises: R Data manipulation and visualization"
pagetitle: "Week 13 exercises"
date: 2026-11-16
date-modified: last-modified
author:
  - name: Menuka Bhandari
    #orcid: 0000-0002-3514-7462
    email: bhandari.72@osu.edu
    affiliation:
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://go.osu.edu/bioinformatics-core
      - name: Dept. of Plant Pathology, Ohio State University
        url: https://plantpath.osu.edu
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
other-links:
  - text: "Week 13 overview"
    icon: check2-all
    href: w13_overview.html
  - text: "w13a: Working with tabular data in R"
    icon: book
    href: w13a_data-wrangling.html
  - text: "w13b: Data visualization in R"
    icon: book
    href: w13b_data-viz.html
language:
  title-block-published: "Week starts on"
  title-block-modified: "Page last modified"
  other-links-title: "Also this week"
---

--------------------------------------------------------------------------------

<br>

## Setting up

1. Open your RStudio Server session at OSC.
   Create a new dir for these exercises, `/fs/ess/PAS3493/people/$USER/week13`,
   and switch to it. _This should be your working dir for the exercises below._

2. Create an empty Quarto file and save it inside the `week13` directory as
   `w13_exercises.qmd`. This should be your main document for these exercises.
   **Make this document self-contained and render it to HTML**.
   In the YAML header, add the author name, date, change theme to cosmo.

3. You can initialize a Git repository either by opening VS Code and following the
   instructions taught by Jelmer, or by using the Terminal pane in RStudio (next to the
   Console). Commit to the repo at least once before you push it to the remote repo.

**Note: If you have not installed `tidyverse` yet, use the `install.packages()` function directly in your console instead of inside the .qmd file**. Apart from installing packages, run all your code in code chunks.
**Use the code chunk option to hide the warnings of your code.**

## Exercises

### R Basics

1. Create a character vector `fav_food` with five names of your favorite food. Replace
third element of the vector with a bird name and extract first and fifth element.

2. Load the `tidyverse` package. We have seen in the class that when we load the
`tidyverse` package, we see many warnings. Use the code chunk option to hide the warning.
Read your `metadata.tsv` file from the
`garrigos/meta` directory and save it as object `metadata`. Write down the data
structure of the `metadata`, number of variables, and rows.

3. In the `metadata` object, replace the `dpi` with `_dpi` of the `time` variable and
`cathemerium` with `cath` of the `treatment` variable.

### Matrices and data frames

4. Look for help for the `matrix` function and create a matrix with numbers 1 to 10 with 2 rows and 5 columns
   and assign it to a new object called `my_matrix`.

5. In week 12's first lecture, we worked with the `iris` data frame,
   which is one of the data sets that comes with R.
   For this exercise, we will use the `mtcars` data frame, which similarly comes with R.
   Start by storing `mtcars` in a new object called `my_cars`,
   then view the first 6 rows of `my_cars`.

6. Check the structure of the `my_cars` data frame.
   Structure of data shows the datatypes of different variables in the data frame.
   Compute the mean of the `mpg` variable of `my_cars` data frame.

7. Show the first 6 rows of the `my_cars` data frame.
   Select columns `mpg`, `cyl`, and `hp` from the `my_cars` data frame and display the first 6 rows.

   ::: {.callout-tip appearance="simple"}
   Remember to load the _tidyverse_ package before using the `select()` function.
   :::

8. Write a single "pipeline" that manipulates `my_cars` by:
   - Selecting columns `mpg` (miles per gallon) and `cyl` (number of cylinders)
   - Only keeping rows with `mpg` greater than 10 and `cyl` equal to 6.
   - Renaming the `cyl` column to `cylinders`
   - Assigning the resulting data frame to an object called `my_cars_filtered`

9. Save the new data frame as a CSV file called `my_cars_filtered.csv` in your working directory.
   In the RStudio "Files" pane,
   check that the file is there and click on it to view it in the editor pane.

### Data wrangling
Instead of creating new objects, always pipe your output unless explicitly stated.

1. List all the datasets available in the `ggplot2` package. Read the data from the
built-in dataset `midwest`. Save it as an object `midwest_datasets` and use `midwest_datasets`
to answer all the questions below.

2. Filter the rows with `poptotal > 30000` and `popdensity > 800`.

3. Select the first 11 variables of the dataset. Create a new column named `asian_ameri` in
`midwest_datasets` object by dividing `popasian` by `popamerindian` and sort
`asian_ameri` in descending order. Save this output as a `new_dataset` object.

4. Compute the total mean population per state and name the mean column as
`poptotal`.

### Quarto and Data Visualization

In class we created a scatter plot, a box plot and a bar graph. For this exercise, you will create the violin plot by reading the ggplot2 documentation using the `midwest_datasets`.

1. Create a violin plot with `state` on the x-axis and `area` on the y-axis. Facet the plot based on `category`.

2. Create a violin plot again with `state` on the x-axis and `poptotal` on the y-axis. Add jitter points to the plot and color just the points based on `category`. Is this point color a global or a local mapping? Please explain.

3. In the above plot change the theme to `theme_bw` and color the `state` manually instead of using default colors. Add the title of the plot using the **code chunk options**. Save this
plot as an object `violin_plot`.

4. Export the `violin_plot` and name the file `violin_plot.png` in your current working directory.


### Publish your repo on GitHub

As before, publish your Git repo on GitHub.

1. Create a repository on GitHub, connect it to your local repo,
   and push your local repo to GitHub.

2. Create a new issue and tag GitHub users `@kstarr791` and `@jelmerp`,
   asking us to take a look at your work.
