---
title: "Week 13: R for data visualization and omics data"
pagetitle: "Week 13 overview"
date: 2026-11-16
date-modified: last-modified
author:
  - name: Menuka Bhandari
    #orcid: 0000-0002-3514-7462
    email: bhandari.72@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://go.osu.edu/bioinformatics-core
      - name: Dept. of Plant Pathology, Ohio State University
        url: https://plantpath.osu.edu
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
other-links:
  - text: "Week 13a Data Visualization"
    icon: book
    href: w13a_data-viz.html
  - text: "w13b: Bioconductor: R for omics data"
    icon: book
    href: w13b_bioconductor.html
language:
  title-block-published: "Week starts on"
  title-block-modified: "Last modified"
  other-links-title: "Also this week"
---

--------------------------------------------------------------------------------

<hr style="height:1pt; visibility:hidden;" />

## Overview

This week we will learn about the **data visualization** in R and install packages using **BiocManager** of
Bioconductor.
For the data visualization, we will use the `ggplot2` package of `Tidyverse`. We have been installing packages 
so far using CRAN. Bioconductor is another way of installing package in R. Bioconductor is a specialized 
repository for **bioinformatics packages in R** that focuses on analysis of high-throughput genomic data.

## Lectures & Learning goals

Some of the things you will learn this week:

#### [Data visualization with ggplot2](./w13a_data-viz.qmd)

- Basic syntax of `ggplot` function in R
- How to create different types of plots using `ggplot2` package in R 
- How to add different layers of information to the plots 
- Export the plots in different formats

#### [Bioconductor: R for omics data](./w13b_bioconductor.qmd)

- Different packages available in `Bioconductor`
- How to **install Bioconductor packages**
- Data structure of Bioconductor
- Use `DECIPHER` package to manipulate DNA sequences and align the genomic sequences

## Assignments and exercises
-   **Graded Assignment 6**: [Data Visualization and Quarto](w13_GA.qmd) [*(Due 11/24)*]{style="color:#bb0000"}

## Further resources
