---
title: "Week 2: Project organization, OSC, and Markdown"
pagetitle: "Week 2 overview"
date: 2026-08-31
date-modified: last-modified
number-sections: false
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://go.osu.edu/bioinformatics-core
      - name: Dept. of Plant Pathology, Ohio State University
        url: https://plantpath.osu.edu
other-links:
  - text: "w2a: Project file organization"
    icon: easel
    href: w2a_project-org.html
  - text: "w2b: OSC"
    icon: easel
    href: w2b_osc.html
  - text: "w2c: VS Code"
    icon: book
    href: w2c_vscode.html
  - text: "w2d: Markdown"
    icon: easel
    href: w2d_markdown.html
  - text: "Week 2 exercises"
    icon: pencil
    href: w2_exercises.html
language:
  title-block-published: "Week starts on"
  title-block-modified: "Page last modified"
  other-links-title: "Also this week"
bibliography: ../references.bib
---

---------

<hr style="height:1pt; visibility:hidden;" />

## Overview

This week is a bit of a potpourri of shorter topics,
introducing you to tools and strategies you'll use throughout the course.

You will explore best practices for project file organization,
get introduced to the Ohio Supercomputer Center (OSC),
and learn how to write Markdown files.
Along the way, you will also get to know VS Code,
the text editor you'll spend a lot of time in during this course.

## Learning goals & lectures

This week's content is divided into the following four lectures,
during which you will learn:

#### A) [**Project file organization and documentation for reproducible research**](./w2a_project-org.qmd) _(Monday)_

- Best practices for organizing and managing your research project files.
- Best practices for documenting your research project.

#### B) [**The Ohio Supercomputer Center (OSC)**](./w2b_osc.qmd) _(Monday and/or Wednesday)_

- What supercomputers are, and why they are useful.
- What resources OSC provides.
- How to access OSC resources through its OnDemand web portal.

#### C) [**An introduction to the VS Code editor**](./w2c_vscode.qmd) _(Wednesday)_

- What VS Code is, and why we use it in this course.
- How to start VS Code at OSC, and find your way around its interface.

#### D) [**An introduction to Markdown**](./w2d_markdown.qmd) _(Wednesday)_

- What Markdown is and why it's useful for research documentation (and beyond).
- The most common Markdown syntax, and how to preview rendered Markdown in VS Code.

## Readings

- @markowetz2015: *Five selfish reasons to work reproducibly*
  ([OSU proxy link {{< fa external-link >}}](https://link-springer-com.proxy.lib.ohio-state.edu/article/10.1186/s13059-015-0850-7){target="_blank"})\
  This short paper gives a light-hearted overview of self-interested reasons to
  perform your research in a reproducible way.

## Assignments & exercises

- **Exercises: [Markdown and project organization](./w2_exercises.qmd)**
- _No assignments this week_

## Optional self-study material

### Books for the entire course

Throughout the course, chapters from these two books are optional readings.
With OSU credentials, both can be freely accessed online via the links below.

- @buffalo2015: [Bioinformatics Data Skills {{< fa external-link >}}](https://search.library.osu.edu/permalink/01OHIOLINK_OSU/1oqfg3i/alma991085518416808507){target="_blank"} \
    **This week**: Preface, Chapter 1 -- *How to Learn Bioinformatics*,
    Chapter 2 -- *Setting Up and Managing a Bioinformatics Project*.

- @allesina2019: [Computing Skills for Biologists {{< fa external-link >}}](https://search.library.osu.edu/permalink/01OHIOLINK_OSU/1n8rc7n/alma991085862322008507){target="_blank"} \
    **This week**: Chapter 0 -- *Building a Computing Toolbox* (Introduction & Section 0.1 only).

### Other

- @noble2009: _A quick guide to organizing computational biology projects_
  ([open access link {{< fa external-link >}}](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000424){target="_blank"})

- @wilson2017: _Good enough practices in scientific computing_
  ([open access link {{< fa external-link >}}](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510){target="_blank"})

- [The Markdown Guide {{< fa external-link >}}](https://www.markdownguide.org){target="_blank"}

- [An interactive Markdown tutorial {{< fa external-link >}}](https://commonmark.org/help/tutorial/){target="_blank"}
