---
title: "Week 10: Workflow and data management"
pagetitle: "Week 10 overview"
date: 2026-10-19
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://go.osu.edu/bioinformatics-core
      - name: Dept. of Plant Pathology, Ohio State University
        url: https://plantpath.osu.edu
other-links:
  - text: "w10a: Workflow management"
    icon: bookmarks
    href: w10a_workflow.html
  - text: "w10b: Data management"
    icon: bookmarks
    href: w10b_data.html
  - text: "Week 10 exercises"
    icon: pencil
    href: w10_exercises.html
language:
  other-links-title: "Also this week"
bibliography: ../references.bib
---

---------

<hr style="height:1pt; visibility:hidden;" />

## Overview

In the past few weeks, we have focused on writing code to complete individual
steps of an omics (RNA-Seq) data processing workflow.
This week, we'll start by zooming out to look at the bigger picture:
how do you organize and run your workflows as a whole?
Next, we'll switch gears and talk about how you should manage and share your data
and other files.

## Learning goals

#### Lecture A: [Workflow management](./w10a_workflow.qmd)

- What a Markdown protocol of your workflow can look like
- How you can automate such workflows with Bash and Slurm,
  and what the associated challenges are
- What "workflow management systems" are,
  and what the advantages of formal pipelines/workflows written with these are
- That you may be able to use publicly available pipelines such as those produced
  by the nf-core initiative

#### Lecture B: [Data management and transfer](./w10b_data.qmd)

- How you can manage your data and share it after publication
- How to transfer files between OSC and other computers like your own
- How to download files at the command-line
- How to manage file permissions

## Readings

- @perkel2019: "Workflow systems turn raw data into scientific knowledge"
- _Consider reading the @grünwald2024 paper mentioned below,_
  _especially if you are working in plant pathology or adjacent fields_

## Assignments & exercises

- [Exercises for this week](./w10_exercises.qmd)
- Ungraded assignment: [Local VS Code installation](./w10_ua_ssh.qmd) [(deadline: Monday Oct 27 at noon)]{style="color:#bb0000"}

## Further resources

- @grünwald2024:
  *"Open Access and Reproducibility in Plant Pathology Research: Guidelines and Best Practices."*
  
- @buffalo2015 ([OSU library link](https://search.library.osu.edu/permalink/01OHIOLINK_OSU/1oqfg3i/alma991085518416808507))
  -- Chapter 4: "_Working with Remote Machines_"
