---
title: "Week 4: Working with files in the Unix shell"
pagetitle: "Week 4 overview"
date: 2026-09-14
date-modified: last-modified
number-sections: false
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://go.osu.edu/bioinformatics-core
      - name: Dept. of Plant Pathology, Ohio State University
        url: https://plantpath.osu.edu
other-links:
  - text: "w4a: Genomics file types"
    icon: easel
    href: w4a_genomics-files.html
  - text: "w4b: Shell files I"
    icon: book
    href: w4b_shell-files1.html
  - text: "w4c: Shell files II"
    icon: book
    href: w4c_shell-files2.html
  - text: "Week 4 exercises"
    icon: pencil
    href: w4_exercises.html
language:
  title-block-published: "Week starts on"
  title-block-modified: "Page last modified"
  other-links-title: "Also this week"
bibliography: ../references.bib
---

---------

<br>

## Overview

This week, we will focus on working with files in the Unix shell.
Because we're going to start working with (DNA/RNA/protein) sequence files,
you'll also get introduced to various types of sequence files.
Finally, you'll learn about the specific files from the example dataset
you'll work with throughout the course.

## Learning goals & lectures

##### A) [**Genomics file types and the example dataset**](./w4a_genomics-files.qmd) _(Monday)_

- What genomics/sequence file types like FASTA, FASTQ, and GFF/GTF are for,
  and what they look like
- How base-call quality scores are coded in FASTQ files
- What the experimental design the course's example dataset's study looks like
- Which files are in our example data set

##### B) [**Working with files in the Unix shell I: The shell as a file browser**](./w4b_shell-files1.qmd) _(Monday/Wednesday)_

Learn to use Unix shell commands to:

- Create, copy, move, rename and delete directories and files
- Select multiple files with a shell wildcard

##### C) [**Working with files in the Unix shell II: Viewing, summarizing and manipulating files**](./w4c_shell-files2.qmd) _(Wednesday)_

Learn to use Unix shell commands to:

- View the contents of text files in various ways
- Use redirection and the pipe to flexibly process the output of commands
- Search within, manipulate, and extract information from text files

## Assignments & exercises

- [Week 4 exercises](./w4_exercises.qmd)
- _No assignments this week_

## Readings

- @garrigós2025:
 _Two avian Plasmodium species trigger different transcriptional tesponses on their vector Culex pipiens_\
 This is the paper associated with the dataset we will use throughout the course,
 starting this week.

## Optional self-study material

- @buffalo2015 --- Chapter 3: "_Remedial Unix Shell_"
  ([OSU library link {{< fa external-link >}}](https://search.library.osu.edu/permalink/01OHIOLINK_OSU/1oqfg3i/alma991085518416808507){target="_blank"})
  
<br>
