---
title: "Week 15: RNA-Seq count data analysis in R"
pagetitle: "Week 15 overview"
date: 2026-11-30
date-modified: last-modified
author:
  - name: Menuka Bhandari
    #orcid: 0000-0002-3514-7462
    email: bhandari.72@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://go.osu.edu/bioinformatics-core
      - name: Dept. of Plant Pathology, Ohio State University
        url: https://plantpath.osu.edu
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
other-links:
  - text: "w15a: Bioconductor: R for omics data"
    icon: book
    href: w15a_bioconductor.html
  - text: "w15b: RNA-Seq count data analysis in R"
    icon: book
    href: w15b_deseq.html
  - text: "Week 15 exercises"
    icon: pencil
    href: w15_exercises.html
  - text: "Final Project progress report"
    icon: pencil
    href: ../FP/FP2.html
language:
  title-block-published: "Week starts on"
  title-block-modified: "Page last modified"
  other-links-title: "Also this week"
---

--------------------------------------------------------------------------------

<hr style="height:1pt; visibility:hidden;" />

## Overview

This is the final week of the R part of the course.
On Monday, we will look at **Bioconductor**, a specialized repository for
bioinformatics packages in R that focuses on the analysis of high-throughput
genomic data.
On Wednesday, we will cover the use of the **DESeq2 package** to identify differentially expressed genes (both 
up-regulated and down-regulated). We will begin by learning how to create a `DESeq2 object`, which consists of 
three key components: `metadata`, `count table`, and `statistical design`. After that, we will perform 
`differential expression analysis` and visualize the results using a `volcano plot`.

## Lectures & Learning goals

Some of the things you will learn this week:

#### [Bioconductor: R for omics data](./w15a_bioconductor.qmd)

- Different packages available in `Bioconductor`
- How to **install Bioconductor packages**
- Data structure of Bioconductor
- Use `DECIPHER` package to manipulate DNA sequences and align the genomic sequences

#### [RNA-Seq count data analysis in R](./w15b_deseq.qmd)

- Create an R object that also incorporates the metadata
- Perform exploratory data analysis including a PCA
- Run a Differential Expression (DE) analysis
- Extract and visualize the DE results

## Assignments and exercises

- [**Final Project progress report**](../FP/FP2.qmd) [_(Due 12/01)_]{style="color:#bb0000"}
- [Exercises for this week](./w15_exercises.qmd)

## Optional self-study material
