---
title: "Week 7: Shell scripts"
pagetitle: "Week 7 overview"
date: 2026-10-05
date-modified: last-modified
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation:
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://go.osu.edu/bioinformatics-core
      - name: Dept. of Plant Pathology, Ohio State University
        url: https://plantpath.osu.edu
other-links:
  - text: "w7a: Shell scripting I"
    icon: book
    href: w7a_scripts1.html
  - text: "w7b: Shell scripting II"
    icon: book
    href: w7b_scripts2.html
  - text: "Advanced shell scripting (optional)"
    icon: book
    href: ../bonus/shell-scripting.html
  - text: "Shell configuration (optional)"
    icon: book
    href: ../bonus/shell-config.html
  - text: "Graded Assignment 3"
    icon: pencil-square
    href: ../GA/GA3.html
language:
  title-block-published: "Week starts on"
  title-block-modified: "Page last modified"
  other-links-title: "Also this week"
bibliography: ../references.bib
---

---------

<hr style="height:1pt; visibility:hidden;" />

## Overview

This week, you will learn how to write **shell scripts** and use them to run programs
with command-line interfaces (CLIs), like various bioinformatics tools.

Looking at the bigger picture, one key goal of this course is to enable you to
submit shell scripts as "batch jobs" at OSC.
This week, we will focus on shell scripts, and in two weeks,
we will move on to submitting these scripts as batch jobs.

_This is a pretty packed week and we may not reach the end of the in-class material_
_on Wednesday. If not, we will finish the remainder at the start of next week._
_(The assignment will only cover material from the first class page.)_

## Learning goals

#### [Shell scripting I: variables and arguments](./w7a_scripts1.qmd) _(Monday/Wednesday)_

- Why it is useful to collect your commands into shell scripts that can be rerun easily
- The basics of shell scripts, including shell script header lines,
  using a script to run FastQC as an example
- Shell variables and how to use them
- Using command-line arguments with your own scripts
- Adding "logging" statements to shell scripts that run command-line programs
- Installing and using the Shellcheck VS Code extension

#### [Shell scripting II: rerunning scripts with loops](./w7b_scripts2.qmd) _(Wednesday)_

- How `for` loops work
- How to use a `for` loop to loop over files and run a shell script many times
- How to keep a record of your analysis steps in a Markdown file
- _Self-study_: How to use parameter expansion to search-and-replace text in variables
- _Self-study_: How to loop over _samples_ (pairs of FASTQ files) rather than individual files

## Exercises & assignments

- **Graded Assignment**: [Software and shell scripts](../GA/GA3.qmd) [_(Due 10/11)_]{style="color:#bb0000"}

## Readings

- The [last part](./w7b_scripts2.qmd#self-study-looping-over-samples)
  of the week's second class page is self-study.

## Optional self-study material

#### On the course website

- [Advanced shell scripting](../bonus/shell-scripting.qmd) --- command substitution,
  `basename` and `dirname`, renaming files with loops, conditionals (`if` statements),
  `while` loops, default values for arguments, standard output vs. standard error,
  and script options.

- [Shell configuration](../bonus/shell-config.qmd) --- the `$PATH`,
  the `~/.bashrc` configuration file, and aliases.

#### Other

- @buffalo2015 --- Chapter 12: "_Bioinformatics Shell Scripting, Writing Pipelines, and Parallelizing Tasks_"
  ([OSU library link {{< fa external-link >}}](https://search.library.osu.edu/permalink/01OHIOLINK_OSU/1oqfg3i/alma991085518416808507){target="_blank"})

<hr style="height:1pt; visibility:hidden;" />
