---
title: "Week 9: Slurm batch jobs at OSC"
pagetitle: "Week 9 overview"
date: 2026-10-03
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://go.osu.edu/bioinformatics-core
      - name: Dept. of Plant Pathology, Ohio State University
        url: https://plantpath.osu.edu
other-links:
  - text: "w9a: Slurm batch jobs I"
    icon: bookmarks
    href: w9a_slurm1.html
  - text: "w9b: Slurm batch jobs II"
    icon: bookmarks
    href: w9b_slurm2.html
  - text: "Week 9 exercises"
    icon: pencil
    href: w9_exercises.html
language:
  other-links-title: "Also this week"
bibliography: ../references.bib
---

---------

<hr style="height:1pt; visibility:hidden;" />

## Overview

As mentioned last week, when you learned about shell scripts:

> The end goal is to be able to submit shell scripts as "batch jobs" at OSC,
which e.g. allows you to run them simultaneously many times!
This is extremely useful because with omics analysis,
it's common to have to run the same step for many samples in parallel.

This week, we'll cover the remaining piece in being able to run bioinformatics
tools efficiently at OSC and beyond:
how to submit your shell scripts as batch jobs.

## Learning goals

#### [Slurm batch jobs -- part I](./w9a_slurm1.qmd)

- Different ways to start "compute jobs":
  via OnDemand, with interactive jobs, and with Slurm batch jobs
- Strategies around requesting appropriate resources for your compute jobs
- Slurm commands like `sbatch` to submit, monitor and manage batch jobs
- How to use Slurm options to request specific resources for your compute jobs

#### [Slurm batch jobs -- part II](./w9b_slurm2.qmd)

- The most common Slurm options, including those to request:
  - More time, cores, and memory for jobs
  - An email notification when jobs e.g. fail or finish
- How to run Slurm jobs in practice, including how to submit many jobs at the same time
- How to make sure that your jobs succeeded

## Exercises & assignments

- [Exercises for this week: Shell scripts](./w9_exercises.qmd)
