---
title: "Week 6: OSC and using software"
number-sections: false
date: 2026-09-28
date-modified: last-modified
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://go.osu.edu/bioinformatics-core
      - name: Dept. of Plant Pathology, Ohio State University
        url: https://plantpath.osu.edu
other-links:
  - text: "w6a: A closer look at OSC"
    icon: book
    href: w6a_osc.html
  - text: "w6b: Using software"
    icon: book
    href: w6b_software.html
  - text: "Week 6 exercises"
    icon: pencil
    href: w6_exercises.html
  - text: "Optional self-study: Conda"
    icon: book
    href: ../bonus/conda.html
language:
  title-block-published: "Week starts on"
  title-block-modified: "Page last modified"
  other-links-title: "Also this week"
bibliography: ../references.bib
---

------------------------------------------------------------------------

<hr style="height:1pt; visibility:hidden;" />

## Overview

This week starts with a closer look at OSC,
expanding on the introduction to OSC in week 2.
Then, you will learn how to use software at OSC,
both programs that OSC has installed and programs that it hasn't.

## Learning goals

Some of the things you will learn this week:

#### A) [A closer look at OSC](./w6a_osc.qmd)

- What "cores" are, and how compute jobs share nodes
- What different types of compute nodes are for
- The difference between memory and storage
- How OSC bills for compute (core hours) and storage
- In which context each of the different OSC storage areas is useful
- Why containers and Conda are useful and reproducible ways to use software

#### B) [Using software](./w6b_software.qmd)

- How to find and load OSC "modules" to use specific programs
- How to find and run Apptainer/Singularity containers to use specific programs
- What the program FastQC does and how you can run it

## Assignments and exercises

- Exercises: [GitHub, OSC, and software](./w6_exercises.qmd)

## Optional self-study material

- Optional self-study content on this site:
  [Software management with Conda](../bonus/conda.qmd)
